### ISSUE TITLE
Full resolution image's link is put to report as absolute link

### ISSUE THREAD

**Issue by Hi-Fi** [eficode/JavaFXLibrary#17]
This is not an issue when running tests locally, and path point to real location. When running tests from Jenkins, path doesn't help as it points to (agent/master) filesystem instead of location accessible with browser.

Might be partially related to #6.

**Comment by sampeson** [comment]
is this still issue? It is put either absolute or relative depending what is set in `Set Screenshot Directory`. With java agent mode this is problem as relative path is used from binary with what library is started...
