### ISSUE TITLE
Support for "Doesn't exists" keywords

### ISSUE THREAD

**Issue by Hi-Fi** [eficode/JavaFXLibrary#18]
Currently there are multiple keywords that wait some element to appear, come visible or activate. It would be good to have items also other way around, that'll wait for something to disappear. 

E.g. in SeleniumLibrary Wait -keywords also have the "negative" version.

**Comment by sampeson** [comment]
All keywords that are checking something. Will add those keywords with asterisk (*), rename with arrow:
`Bounds Should Be Equal
Bounds Should Not Be Equal*
Images Should Match
Images Should Not Match
Node Should Be Enabled
Node Should Be Disabled => Node Should Not Be Enabled
Node Should Be Focused
Node Should Not Be Focused
Node Should Be Hoverable
Node Should Not Be Hoverable*
Node Should Be Visible
Node Should Be Invisible => Node Should Not Be Visible
Node Should Have Text
Node Should Not Have Text
Radio Button Should Be Selected
Radio Button Should Not Be Selected
Toggle Button Should Be Selected
Toggle Button Should Not Be Selected
Wait Until Element Exists
Wait Until Element Does Not Exists*
Wait Until Node Is Enabled
Wait Until Node Is Not Enabled*
Wait Until Node Is Visible
Wait Until Node Is Not Visible*
Wait Until Progress Bar Is Finished
Window Should Be Focused
Window Should Not Be Focused
Window Should Be Showing => Window Should Be Visible
Window Should Not Be Visible*`
