### ISSUE TITLE
Can we test Oracle application form with using JavaFXLibrary? If yes then can anyone please help me to start.

### ISSUE THREAD

**Issue by pankajjoshi-hub** [eficode/JavaFXLibrary#59]

**Comment by sampeson** [comment]
Oracle Java 8 application with JavaFX UI should be possible to test with this Robot library. Instructions how to do it can be find from master [README.md](https://github.com/eficode/JavaFXLibrary/blob/master/README.md). This could be discussed in [discussions](https://github.com/eficode/JavaFXLibrary/discussions). Please describe your Java and JavaFXLibrary version in use, what do you want to achieve etc. there. 

Will close this now.
